spring:
  cloud:
    nacos:
      discovery:
        # server-addr: localhost:8848
        # 换成nginx的8080端口 做集群
        server-addr: localhost:8848
        namespace: f9ce362e-d3de-4d52-aadb-91ece67be28c


  application:
    name: frankMall-auth-server
  thymeleaf:
    cache: false
  redis:
    host: 127.0.0.1
    #    password: 11111111
    port: 6379
  session:
    store-type: redis

server:
  port: 20000

feign:
  httpclient:
    connection-timeout: 5000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000