spring:
  datasource:
    url: jdbc:mysql://localhost/gulimall_ums
    username: root
    password: 11111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # server-addr: localhost:8848
        # 换成nginx的8080端口 做集群
        server-addr: localhost:8848
        namespace: f9ce362e-d3de-4d52-aadb-91ece67be28c
  application:
    name: frankMall-cart
  thymeleaf:
    cache: false
server:
  port: 40000

feign:
  httpclient:
    connection-timeout: 5000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

frankmall:
  thread:
    core-size: 40
    max-size: 100
    keep-alive-time: 10