spring:
  cloud:
    nacos:
      discovery:
        # server-addr: localhost:8848
        # 换成nginx的8080端口 做集群
        server-addr: localhost:8848
        namespace: f9ce362e-d3de-4d52-aadb-91ece67be28c
  application:
    name: frankMall-search



server:
  port: 12000