spring:
  datasource:
    url: jdbc:mysql://localhost/gulimall_ums
    username: root
    password: 11111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # server-addr: localhost:8848
        # 换成nginx的8080端口 做集群
        server-addr: localhost:8848
        namespace: f9ce362e-d3de-4d52-aadb-91ece67be28c
  application:
    name: frankMall-member
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    port: 6379

mybatis-plus:
  global-config:
    db-config:
      id-type: auto


server:
  port: 8000
  servlet:
    session:
      timeout: 30m

logging:
  level:
    com.lxc.frankmall.member.dao: debug
